version: '3.6'
services:
  portainer:
    image: portainer/portainer-ce:2.0.1-alpine
    restart: always
    ports:
      - "9000:9000"  # UI
      # - "8000:8000"  # TCP tunnel for Edge agents (optional)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - portainer_data:/data
